{{- if .Values.pgsql_transport.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgsql_transport.name | replace "_" "-" }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.pgsql_transport.data }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
