{{- if .Values.pgsql_mailman_recipients.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgsql_mailman_recipients.name | replace "_" "-"}}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.pgsql_mailman_recipients.data }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
