{{- if .Values.mx_tls.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mx_tls.name | replace "_" "-" }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.mx_tls.data.tls_crt | b64enc }}
  tls.key: {{ .Values.mx_tls.data.tls_key | b64enc }}
{{- end }}
