{{- if .Values.smtp_password.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.smtp_password.name | replace "_" "-" }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.smtp_pasword.data }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
