{{- if .Values.sasl_db.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sasl_db.name | replace "_" "-" }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.sasl_db.data }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
